spring.application.name=hrm-backend
server.port=8080

# PostgreSQL Connection Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/hrm_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
app.jwt.secret=${APP_JWT_SECRET:9a4f2c8d7e1b5a3f6c9d2e8a4b7c1e5f8a3b6c9d2e7f4a1b5c8d2e9f6a3b7c1e}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true